pipeline{
	agent any
    
    	environment {
        	WORKSPACE_JENKINS = '$WORKSPACE'
	}	
    	stages{
        	stage('Git'){
            		steps{
		                git 'https://github.com/flaviomrjr/ci-cd.git'
		        }
        	}
        	stage('Deploy'){
            		steps{
            			ansiblePlaybook(inventory: '/etc/ansible/hosts', playbook: '${WORKSPACE}/Avec/ansible/playbooks/bluegreen.yml')	
	    		}
        	}
		stage('PostBuild'){
	    		steps{
				script {
					step([$class: "RundeckNotifier",
					includeRundeckLogs: true,
					jobId: "3733557a-ebb9-414c-989c-99f0a45818e3",
					nodeFilters: "",
					rundeckInstance: "Rundeck",
					shouldFailTheBuild: true,
					shouldWaitForRundeckJob: true,
					tags: "",
					taillog: true])
				}
			}
		}		
	}
}
